### ISSUE TITLE
Game Not Randomizing

### ISSUE THREAD

**Issue by WearableSnake** [Marechal-L/Dark-Souls-III-Archipelago-client#10]
(Copy and paste from Discord)
I followed the directions to put in the .dll file in the /Game/ directory.

When starting the game, the CMD prompt opens. I put in the details of the room, along with my ID. It then takes a moment before connecting.

Everything 'looks' like it is working, but when I pick up items they are not random. For example, the broken sword after the first boss.

The only thing I can think of, unless I'm missing something, is that the version of the game I'm running does not want to work with this randomizer. Since the Steam version is 1.15.2, and the provided downpatcher does not work, I looked online and found a 1.15 version of the game.

When I replace the original and load it up, it shows 1.15 and seems to work just fine, except for the lack of randomization.

I found out that the downpatching information on the SpeedRunner website is out of date since Steam had some kind of update.

From there, I realized I could use the Steam Console to directly download older depots.

I specifically used this:
download_depot 374320 374321 4471176929659548333

Which then downloaded it successfully. From there I deleted everything in my DS3 folder, then moved the freshly downloaded stuff into it.

The game loads, shows 1.15. I put in the AP stuff, the command prompt pops up, can connect to the server.

It still does not randomize my content. With the instructions being so short, I have no idea what I could be missing at this point.

**Comment by WearableSnake** [comment]
Found the solution:

So, I was misreading something about the connect script, but also, the connect script isn't properly throwing errors
So I was putting in:
/connect archipelago.gg:42241 1
Instead of
/connect archipelago.gg:42241 Snake
Putting in '/connect archipelago.gg:42241 1' does not throw any errors, and still states that you have connected to the server
I was putting in 1, because I was thinking slot number, not slot name.

If it could throw an error at the wrong input it would fix this problem.

**Comment by Marechal-L** [comment]
Thanks for reporting, I added "Connection refused feedback" on the next 2.1.1 version
