### ISSUE TITLE
Small Lothric Banner

### ISSUE THREAD

**Issue by DanZinagri** [Marechal-L/Dark-Souls-III-Archipelago-client#12]
This sorta qualifies as an issue so i thought i'd place this here.
If selecting the late basin of vows so you don't have to fight the dancer in the first 3 minutes of the game, the game then gets locked behind the Small Lothric Banner and Small Doll as the two major checks that need to occur (excluding the lord ashes to proceed to the final boss).

The problem is when this setting occurs in a multi-person randomizer it regularly places that Small Lothric Banner at about 1/3 to 1/2 of the way through the entire randomizer run for the group. This means within 10-30 minutes you can 100% all available checks, and then be stuck. Every single time i did this the game would leave me stuck unable to proceed for 5+hours.

Checking the spoiler log over multiple generations we realized its beacause it seems to not properly weigh the importance of this first check.

I'm not sure how this plays with the archipelago framework, but this really needs to have some sort of check to disable shuffling of it, or at the very least give it some sort of weighting so its not multiple hours of being unable to proceed; as even if we immediately used the spoiler log and made a b-line for all required items it still effectively seems to expect the Dark Souls 3 player to not play for multiple hours, which is bad, considering how much content exists before the Small doll check.
This is extra bad because by the time i was allowed to move forward, everyone else was then stuck as i needed to play through from that very beggining point of Vordt, all the way to archdragon peak before i was able to give out required items for everyone else; which meant even rushing at top speed I was going to be holding up the entire run because of how absolutely De-synchronized Dark Souls 3 is from the rest of the run.

**Comment by Br00ty** [comment]
A very popular thing to do is to put the "Small Lothric Banner" in the `start_inventory` or `local_items` option in your yaml settings, then you'll either start with your SLB, or you'll find your Banner in your own world, and if you have 'late basin' on then you will find it in either Fire Sanctuary or High Wall of Lothric
![image](https://github.com/Marechal-L/Dark-Souls-III-Archipelago-client/assets/83629348/2c28d234-659d-4e87-a77f-f79b8dbe291b)
