### ISSUE TITLE
DS3 crashes on stream

### ISSUE THREAD

**Issue by nex3** [Marechal-L/Dark-Souls-III-Archipelago-client#18]
When I try to stream the Dark Souls 3 window to Discord when the Archipelago mod is installed, whether it's connected to the server or not, it crashes immediately with the following window:

![image](https://github.com/Marechal-L/Dark-Souls-III-Archipelago-client/assets/188/c49dff29-d777-4bcf-80a9-0e8c350f0411)

**Comment by Marechal-L** [comment]
Hi, I also encountered this issue a long time ago and I asked Br00ty to refresh my memories.
This was related to the AP mod running along modengine and we fixed this by setting blockNetworkAccess to true in the modengine.ini.
Another way to share your game was to share the entire screen which doesn't seem to make it crash.

Please let me know if it resolved your issue

**Comment by nex3** [comment]
I am running it along with ModEngine, but `blockNetworkAccess=1` is already set and it's still crashing. I can share my screen, but I'd much prefer to share my application window if possible.

**Comment by Marechal-L** [comment]
Sorry I just tried and the param should be set to 0 as follow `blockNetworkAccess=0`.

I don't know what's happening here but AP mod and Discord probably try to access the same part of the "low level hook to block game from ever connecting to the internet" mentioned by modEngine.

**Comment by nex3** [comment]
Confirm that `blockNetworkAccess=0` works.
